WebSite/ViewModels/MyRequestsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using SentimentAnalysisApp.SharedModels;
using WebSite.Models;

namespace WebSite.ViewModels {
    public enum Category: int {
        All,
        Pending,
        Completed,
        Drafts
    }

    public class MR_BannerMsg: BannerMsg {
        public static readonly MR_BannerMsg CreateOk = new MR_BannerMsg( "Your Request was successfully scheduled for execution.", "alert-success" );
        public static readonly MR_BannerMsg ErrorNotCreated = new MR_BannerMsg( "Unfortunately, your Request could not be created. Please try again later.", "alert-danger" );
        public static readonly MR_BannerMsg ErrorNotExecuted = new MR_BannerMsg( "Unfortunately, your Request could not be be programmed for execution right now, and was saved to your Drafts. Please try again later.", "alert-danger" );
        public static readonly MR_BannerMsg ErrorAlreadyExecuting = new MR_BannerMsg( "This Request is already under execution.", "alert-danger" );
        public static readonly MR_BannerMsg ErrorCannotInspect = new MR_BannerMsg( "This Request cannot be inspected right now.", "alert-danger" );

        private MR_BannerMsg(string Text, string AlertType)
            : base( Text, AlertType ) {
        }
    }

    public class MyRequestsViewModel {
        public IEnumerable<FESearchRequest> TheSearchRequests { get; set; }
        public Category TheCategory { get; set; }
        public MR_BannerMsg TheBannerMsg { get; set; }
    }

    public class InspectSReqsViewModel {
        public FESearchRequest TheSearchRequest { get; set; }
        public MR_BannerMsg TheBannerMsg { get; set; }
    }

    public class CreateSReqViewModel {        
        public FESearchRequest TheSearchRequest { get; set; }
            
        [Display( Name = "Sources " )]
        [CheckboxListNotEmpty( ErrorMessage = "You must select at least one source." )]
        public List<SourceOption> SelectedSources { get; set; }

        public CreateSReqViewModel() {
            TheSearchRequest = new FESearchRequest();
            SelectedSources = new List<SourceOption>();
        }

        public CreateSReqViewModel(string[] previousOptions) : this() {
            foreach(var prevOption in previousOptions) {
                var option = (SourceOption)Enum.Parse( typeof( SourceOption ), prevOption );
                SelectedSources.Add( option );
            }
        }
    }

    [AttributeUsage( AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false )]
    sealed public class CheckboxListNotEmptyAttribute: ValidationAttribute {
        public override bool IsValid(object value) {
            var theList = (List<SourceOption>)value;
            return (theList.Count != 0) ? true : false;
        }
    }

}

WebSite/Controllers/MyRequestsController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Http.Results;
using System.Net.Http;
using System.Web.Configuration;

using Microsoft.AspNet.Identity;

using SentimentAnalysisApp.SharedModels;
using WebSite.Models;
using WebSite.ViewModels;

namespace WebSite.Controllers {

    [Authorize]
    public class MyRequestsController: FluentDisplayController {

        private FESearchRequestsController TheSReqController = new FESearchRequestsController();
        private FEExecutionsController TheExecsController = new FEExecutionsController();
        private static HttpClient clientBEserver = new HttpClient {
            BaseAddress = new System.Uri( WebConfigurationManager.AppSettings["WebApiProvider-URI"] )
        };


        [HttpGet]
        public ActionResult Index(string category) {
            MyRequestsViewModel theVM = new MyRequestsViewModel();
            Status theStatus;

            try {
                theVM.TheCategory = (Category)Enum.Parse( typeof( Category ), category );
                switch(theVM.TheCategory) {
                    case Category.Drafts:
                        theStatus = Status.New;
                        break;
                    case Category.Pending:
                        theStatus = Status.Executing;
                        break;
                    case Category.Completed:
                        theStatus = Status.Fulfilled;
                        break;
                    default:
                        throw new Exception();
                }

                theVM.TheSearchRequests = TheSReqController.GetFESearchRequests( User.Identity.GetUserId(), theStatus );
            } catch {
                theVM.TheCategory = Category.All;
                theVM.TheSearchRequests = TheSReqController.GetFESearchRequests( User.Identity.GetUserId() );
            }
            theVM.TheSearchRequests.OrderByDescending( sReq => sReq.TheLatestExecution.StartedOn );
            theVM.TheBannerMsg = (MR_BannerMsg)LoadBannerMsg();

            return View( theVM );
        }


        [HttpGet]
        public async Task<ActionResult> Inspect(int id = -1) {
            if(id == -1) {
                return RedirectTo( "Index" );
            }
            InspectSReqsViewModel theVM = new InspectSReqsViewModel();

            var response = await TheSReqController.GetFESearchRequest( id );
            if(response.GetType() == typeof( OkNegotiatedContentResult<FESearchRequest> )) {
                theVM.TheSearchRequest = ((OkNegotiatedContentResult<FESearchRequest>)response).Content;
                theVM.TheBannerMsg = theVM.TheBannerMsg = (MR_BannerMsg)LoadBannerMsg();

                return View( "Inspect", theVM );
            } else {
                return RedirectTo( "Index", MR_BannerMsg.ErrorCannotInspect );
            }
        }

        [HttpGet]
        [ChildActionOnly]
        public PartialViewResult ViewExecutions(int searchRequestID) {
            var theExecutions = TheExecsController.GetFEExecutions( searchRequestID );
            return PartialView( "_ViewExecutions", theExecutions );
        }

        [HttpGet]
        public ActionResult Create() {
            if(ModelErrorHappened() == false) {
                return View( new CreateSReqViewModel() );
            } else {
                LoadModelState();

                //Retrieve the previous CheckboxList selection 
                var p = ModelState["SelectedSources"];
                if(p != null && p.Value != null) {
                    string[] previousOptions = (string[])p.Value.RawValue;
                    return View( new CreateSReqViewModel( previousOptions ) );
                } else {
                    return View( new CreateSReqViewModel() );
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateSReqViewModel theVM) {
            if(ModelState.IsValid) {
                FESearchRequest newSearchRequest = theVM.TheSearchRequest;

                newSearchRequest.TheStatus = Status.New;
                newSearchRequest.TheUserID = User.Identity.GetUserId();
                newSearchRequest.TheSelectedSources.SetFromList( theVM.SelectedSources );

                var response = await TheSReqController.PostFESearchRequest( newSearchRequest );
                if(response.GetType() == typeof( CreatedAtRouteNegotiatedContentResult<FESearchRequest> )) {
                    FESearchRequest createdSearchRequest = ((CreatedAtRouteNegotiatedContentResult<FESearchRequest>)response).Content;
                    return await Execute( createdSearchRequest );
                } else {
                    return RedirectTo( "Index", MR_BannerMsg.ErrorNotCreated );
                }

            } else {
                return RedirectTo( "Create" );
            }
        }

        public async Task<ActionResult> Execute(int searchRequestID) {

            var response = await TheSReqController.GetFESearchRequest( searchRequestID );
            if(response.GetType() == typeof( OkNegotiatedContentResult<FESearchRequest> )) {
                FESearchRequest searchRequest = ((OkNegotiatedContentResult<FESearchRequest>)response).Content;
                return await Execute( searchRequest );
            } else {
                return RedirectTo( "Inspect", MR_BannerMsg.ErrorNotExecuted, routeValues: new { id = searchRequestID } );
            }

        }

        private async Task<ActionResult> Execute(FESearchRequest searchRequest) {
            Status previousStatus = searchRequest.TheStatus;
            if(previousStatus == Status.Executing) {
                return RedirectTo( "Inspect", MR_BannerMsg.ErrorAlreadyExecuting, routeValues: new { id = searchRequest.ID } );
            }
            searchRequest.TheStatus = Status.Executing;
            await TheSReqController.UpdateFESearchRequestStatus( searchRequest.ID, Status.Executing );

            // Send the Search Request to the BE Server for execution
            try {
                var response = await clientBEserver.PostAsJsonAsync(
                                WebConfigurationManager.AppSettings["WebApiProvider-SubmitRoute"],
                                (BaseSearchRequest)searchRequest );

                if(response.IsSuccessStatusCode) {
                    searchRequest.LastExecutionCreatedOn = DateTime.Now;
                    await TheSReqController.UpdateFESearchRequest( searchRequest.ID, searchRequest );
                    return RedirectTo( "Inspect", MR_BannerMsg.CreateOk, routeValues: new { id = searchRequest.ID } );
                } else {
                    await TheSReqController.UpdateFESearchRequestStatus( searchRequest.ID, previousStatus );
                    return RedirectTo( "Inspect", MR_BannerMsg.ErrorNotExecuted, routeValues: new { id = searchRequest.ID } );
                }
            } catch {
                await TheSReqController.UpdateFESearchRequestStatus( searchRequest.ID, previousStatus );
                return RedirectTo( "Inspect", MR_BannerMsg.ErrorNotExecuted, routeValues: new { id = searchRequest.ID } );
            }
        }    
        

    }
}

WebSite/Views/MyRequests/Create.cshtml
@using System
@using MvcCheckBoxList.Model
@using SentimentAnalysisApp.SharedModels
@using WebSite.ViewModels
@model CreateSReqViewModel

@{
    ViewBag.TitleTail = "Create Request";
}

@section Styles {
    <link href="@Url.Content( "~/Content/customForms.css" )" rel="stylesheet" type="text/css" />
    <link href="@Url.Content( "~/Content/myRequests.css" )" rel="stylesheet" type="text/css" />
}

@section Scripts{
    <script src="@Url.Content( "~/scripts/customForms.js" )"></script>
    <script src="@Url.Content( "~/scripts/myRequestsCreate.js" )"></script>
}

<section class="container-fluid form-section">
    <h1>New Request</h1>
    <h3>Search what the users of the social media and other sources, <span class="visible-md visible-lg"></span> feel about something.</h3>
    <br />

    @using(Html.BeginForm( "Create", "MyRequests", FormMethod.Post, new { @class = "theForm post-form", role = "form" } )) {
        @Html.AntiForgeryToken()

        <div class="form-group float-label-control">
            <h3>Word of Interest</h3>
            <p>Select the word or phrase you are interested in.</p>
            <br />

            @Html.LabelFor( m => m.TheSearchRequest.TheSearchKeyword, new { @class = "" } )
            @Html.TextBoxFor( m => m.TheSearchRequest.TheSearchKeyword, new { @class = "form-control", placeholder = "coca cola cherry", spellcheck = "false" } )
        </div>
        <div class="validation-msg">
            @Html.ValidationMessageFor( m => m.TheSearchRequest.TheSearchKeyword, "" )
        </div>

        <div class="form-group">
            <h3>Available Sources</h3>
            <p>Where do you want the data to be gathered from?</p>
            <br />

            <div class="theCheckboxList">
                @Html.CheckBoxListFor( model => model.SelectedSources,
                                model => MiningSource.AllSources(),
                                option => option,
                                option => Enum.GetName( typeof( SourceOption ), option ),
                                model => model.SelectedSources,
                                Position.Vertical
                                )
            </div>
        </div>
        <div class="validation-msg">
            @Html.ValidationMessageFor( m => m.SelectedSources, "" )
        </div>

        <button type="submit" class="post-button btn btn-default basic">Create</button>
        <i class="loading-banner fa fa-spinner fa-pulse fa-3x fa-fw" style="display: none"></i>
    }

</section>

WebSite/Views/MyRequests/Index.cshtml
@using System
@using WebSite.Models
@using WebSite.ViewModels
@model MyRequestsViewModel

@{
    ViewBag.TitleTail = "MyRequests";
}

@section Styles {
    <link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content( "~/Content/myRequests.css" )" rel="stylesheet" type="text/css" />
    <link href="@Url.Content( "~/Content/fluentDisplay.css" )" rel="stylesheet" type="text/css" />
}

@section Scripts{
    <script type="text/javascript" src="@Url.Content( "~/scripts/myRequestsIndex.js" )"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
}

@if(@Model.TheBannerMsg != null) {
    <div id="bannerMsg" class="alert alert-dismissable @Model.TheBannerMsg.AlertType">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @Model.TheBannerMsg.Text
    </div>
}

<section class="container-fluid">
    @{ string title = Model.TheCategory.ToString();
        title += Model.TheCategory != Category.Drafts ? " Requests" : "";

        int rowNum = 0;
        string sourcesHideClass = "";
        string inspectButHideClass = "";
        string dateCreatedHideClass = "";
        string dateStartedHideClass = "";

        var category = Model.TheCategory;
        if(category == Category.All) {
            sourcesHideClass = "hidden-md hidden-sm hidden-xs";
            inspectButHideClass = "";
            dateCreatedHideClass = "hidden-xs";
            dateStartedHideClass = "hidden-xs";
        } else if(category == Category.Pending || category == Category.Completed) {
            sourcesHideClass = "hidden-sm hidden-xs";
            inspectButHideClass = "";
        }

    }

    <h1>@title</h1>
    <br />

    @if(Model.TheSearchRequests == null || Model.TheSearchRequests.Count() == 0) {
        var reqs = Model.TheCategory == Category.All ? "requests" : @title.ToLower();
        <p>There are no @reqs at the moment.</p>
    } else {
        <table class="table text-center sortableTable">
            <thead>
                <tr>
                    <th>Word of Interest</th>
                    <th class="@sourcesHideClass">Selected Sources</th>
                    <th class="@dateCreatedHideClass">Date Created</th>
                    @{
                        if(category == Category.Drafts || category == Category.All) {

                        }
                        if(category == Category.Pending || category == Category.All) {
                            <th class="@dateStartedHideClass">Date Exec Started</th>
                        }
                        if(category == Category.Completed || category == Category.All) {
                            <th>Date Exec Completed</th>
                        }
                        if(category == Category.Pending || category == Category.Completed || category == Category.All) {
                            <th class="noSort">Latest Results</th>
                        }
                        if(category == Category.All) {
                            <th>Status</th>
                        }

                    }
                    <th class="noSort @inspectButHideClass"></th>
                </tr>
            </thead>
            <tbody>

                @foreach(var item in Model.TheSearchRequests) {
                    rowNum++;
                    <tr class="clickable-row" data-href="@Url.Action( "Inspect", "MyRequests", routeValues: new { id = item.ID } )">
                        <td>@item.TheSearchKeyword</td>
                        <td class="@sourcesHideClass">@item.TheSelectedSources.TheSelection.ToString()</td>
                        <td class="@dateCreatedHideClass">@item.CreatedOn.Value.ToString( "dd MMMM yy" )</td>

                        @{
                            if(category == Category.Drafts || category == Category.All) {

                            }
                            if(category == Category.Pending || category == Category.All) {
                                if(item.LastExecutionCreatedOn != null) {
                                    <td class="@dateStartedHideClass">@item.LastExecutionCreatedOn.Value.ToString( "dd MMMM yy" )</td>
                                } else {
                                    <td class="@dateStartedHideClass"></td>
                                }
                            }
                            if(category == Category.Completed || category == Category.All) {
                                if(item.TheLatestExecution != null && item.TheLatestExecution.FinishedOn != null) {
                                    <td>@item.TheLatestExecution.FinishedOn.Value.ToString( "dd MMMM yy" )</td>
                                } else {
                                    <td></td>
                                }
                            }
                            if(category == Category.Pending || category == Category.Completed || category == Category.All) {
                                if(item.TheLatestExecution != null) {
                                    var posScore = item.TheLatestExecution.TheResults.ThePositiveScore.ToString( "0.0" );
                                    var negScore = item.TheLatestExecution.TheResults.TheNegativeScore.ToString( "0.0" );
                                    <td>
                                        <p class="posScore">@posScore%<i class="fa fa-thumbs-up"></i></p>
                                        <p class="negScore">@negScore%<i class="fa fa-thumbs-down"></i></p>
                                    </td>
                                } else {
                                    <td></td>
                                }
                            }
                            if(category == Category.All) {
                                string labelType = "label-default";
                                switch(item.TheStatus) {
                                    case Status.New:
                                        labelType = "label-primary";
                                        break;
                                    case Status.Executing:
                                        labelType = "label-warning";
                                        break;
                                    case Status.Fulfilled:
                                        labelType = "label-success";
                                        break;
                                }
                                <td><span class="label @labelType">@item.TheStatus.ToString()</span></td>
                            }

                        }


                        <td class="inspect-button @inspectButHideClass">
                            <a href="@Url.Action( "Inspect", "MyRequests", routeValues: new { id = item.ID } )"><i class="fa fa-eye"></i></a>
                        </td>
                    </tr>
                            }

            </tbody>
        </table>
                            }

</section>

WebSite/Views/MyRequests/Inspect.cshtml
@using System
@using WebSite.Models
@using WebSite.ViewModels
@model InspectSReqsViewModel

@{
    ViewBag.TitleTail = "Inspect Request";
}

@section Styles {
    <link href="@Url.Content( "~/Content/myRequests.css" )" rel="stylesheet" type="text/css" />
    <link href="@Url.Content( "~/Content/fluentDisplay.css" )" rel="stylesheet" type="text/css" />
}

@section Scripts{
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="@Url.Content( "~/scripts/myRequestsInspect.js" )"></script>
}

@if(@Model.TheBannerMsg != null) {
    <div id="bannerMsg" class="alert alert-dismissable @Model.TheBannerMsg.AlertType">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @Model.TheBannerMsg.Text
    </div>
}

@{
    string labelType = "label-default";
    switch(Model.TheSearchRequest.TheStatus) {
        case Status.New:
            labelType = "label-primary";
            break;
        case Status.Executing:
            labelType = "label-warning";
            break;
        case Status.Fulfilled:
            labelType = "label-success";
            break;
    }
    string headerColType = "header";
    string valueColType = "";

}

<section class="inspect container-fluid ">
    <h2>Inspect Request</h2>
    <br />

    <h3>Basic Info</h3>

    <div class="view-text">
        <div class="@headerColType">
            <h4>Word of Interest:</h4>
        </div>
        <div class="@valueColType">
            @Model.TheSearchRequest.TheSearchKeyword
        </div>
    </div>

    <div class="view-text">
        <div class="@headerColType">
            <h4>Status:</h4>
        </div>
        <div class="@valueColType">
            <div>
                <span class="label @labelType">@Model.TheSearchRequest.TheStatus.ToString()</span>
            </div>
        </div>
    </div>

    <div class="view-text">
        <div class="@headerColType">
            <h4>Initial Creation Date:</h4>
        </div>
        <div class="@valueColType">
            <div>
                @Model.TheSearchRequest.CreatedOn.Value.ToString( "dd MMMM yy, hh:mm" )
            </div>
        </div>
    </div>

    <div class="view-text">
        <div class="@headerColType">
            <h4>Selected Sources:</h4>
        </div>
        <div class="@valueColType">
            <div>
                @Model.TheSearchRequest.TheSelectedSources.TheSelection.ToString()
            </div>
        </div>
    </div>

    @if(Model.TheSearchRequest.TheLatestExecution != null) {
        <div class="view-text">
            <div class="@headerColType">
                <h4>Latest Results:</h4>
            </div>
            <div class="@valueColType">
                <div class="scores">
                    <p class="posScore">@Model.TheSearchRequest.TheLatestExecution.TheResults.ThePositiveScore.ToString( "0.0" )%<i class="fa fa-thumbs-up"></i></p>
                    <p class="negScore">@Model.TheSearchRequest.TheLatestExecution.TheResults.TheNegativeScore.ToString( "0.0" )%<i class="fa fa-thumbs-down"></i></p>
                </div>
            </div>
        </div>
    }

</section>

@if(Model.TheSearchRequest.TheStatus != Status.Executing) {
    <section class="inspect container-fluid ">
        <h3>Execute the Request</h3>

        @if(Model.TheSearchRequest.TheStatus == Status.New) {
            <p>See what the users feel, by executing this Request.</p>
        } else if(Model.TheSearchRequest.TheStatus == Status.Fulfilled) {
            <p>Get updated results about this Request by executing it again.</p>
        }

        <a class="btn btn-default basic" href="@Url.Action( "Execute", "MyRequests", routeValues: new { searchRequestID = Model.TheSearchRequest.ID } )" role="button">EXECUTE</a>
    </section>
}

@if(Model.TheSearchRequest.TheStatus != Status.New) {
    @Html.Action( "ViewExecutions", routeValues: new { searchRequestID = Model.TheSearchRequest.ID } )
}

WebSite/Views/MyRequests/_ViewExecutions.cshtml
@model IEnumerable<WebSite.Models.FEExecution>

<section class="inspect container-fluid">
    <h3>Executions</h3>
    <br />

    @if(Model == null || Model.Count() == 0) {
        <p>There are no executions data available at the moment.</p>
    } else {
        <div class="row">

            <div class="col-lg-6">
                <h4>Details:</h4>
                <br />
                <table>
                    <thead>
                        <tr>
                            <th>Date Started</th>
                            <th>Date Completed</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var exec in Model) {

                            <tr class="update-chart-basic">
                                <td>@exec.StartedOn.Value.ToString( "dd MMMM yy" )</td>
                                <td>@exec.FinishedOn.Value.ToString( "dd MMMM yy" )</td>

                                <td class="theDate" style="display:none">@exec.FinishedOn.Value.ToString( "yyyy MM dd" )</td>
                                <td class="posScore" style="display:none">@exec.TheResults.ThePositiveScore</td>
                                <td class="negScore" style="display:none">@exec.TheResults.TheNegativeScore</td>
                                <td class="inspect-button">
                                    <a><i class="fa fa-pie-chart "></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

            <div id="chart-basic-container" class="col-lg-6">
                <h4>Results:</h4>
                <p class="chart-error" style="display:none">There was and error while loading the chart.</p>
                <div id="chart-basic"></div>
            </div>
        </div>
    }

</section>

@if(Model != null && Model.Count() != 0) {
    <section class="inspect container-fluid">
        <h3>Sentiment over time</h3>
        <p>Observe how the overall sentiment (user opinions) develops over different points (executions) in time.</p>
        <br />

        <div id="chart-graph-container">
            <p class="chart-error" style="display:none">There was and error while loading the chart.</p>
            <div id="chart-graph"></div>
        </div>
    </section>
}