WebSite/Controllers/UserRolesController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

using WebSite.Models;
using WebSite.ViewModels;

namespace WebSite.Controllers {

    public class UserRolesController: FluentDisplayController {
        private ApplicationDbContext userDb = new ApplicationDbContext();

        public ActionResult Index() {
            UserRolesViewModel theVM = new UserRolesViewModel();

            theVM.TheRolesList = from r in userDb.Roles
                                 select new SelectListItem {
                                     Value = r.Id.ToString(),
                                     Text = r.Name
                                 };

            theVM.TheUsersList = from u in userDb.Users
                                 select new SelectListItem {
                                     Value = u.Id.ToString(),
                                     Text = u.Email
                                 };

            theVM.TheBannerMsg = (UR_BannerMsg)LoadBannerMsg();

            theVM.RolesForTheUser = (IEnumerable<string>)TempData["rolesForTheUser"];
            theVM.TheUserID = (string)TempData["TheUserID"];

            return View( theVM );
        }


        [HttpGet]
        [ChildActionOnly]
        public PartialViewResult CreateRole() {
            if(ModelErrorHappened() == false) {
                return PartialView( "_CreateRole", new UserRoleInfo() );
            } else {
                LoadModelState();
                return PartialView( "_CreateRole" );
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRole(UserRoleInfo newRoleInfo) {
            if(ModelState.IsValid) {
                userDb.Roles.Add( new IdentityRole() {
                    Name = newRoleInfo.roleName
                } );

                userDb.SaveChanges();
                return RedirectTo( "Index", UR_BannerMsg.RoleCreated );
            } else {
                return RedirectTo( "Index" );
            }
        }


        public ActionResult DeleteRole(string roleID) {

            var theRole = from r in userDb.Roles
                          where r.Id == roleID
                          select r;
            if(theRole != null) {
                userDb.Roles.Remove( theRole.FirstOrDefault() );
                userDb.SaveChanges();
                return RedirectTo( "Index", UR_BannerMsg.RoleDeleted );
            } else {
                return RedirectTo( "Index" );
            }

        }

        public ActionResult EditRole(string roleID) {
            var theRole = (from r in userDb.Roles
                           where r.Id == roleID
                           select r).FirstOrDefault();

            var theRoleInfo = new UserRoleInfo {
                roleName = theRole.Name,
                roleID = theRole.Id
            };

            if(theRole != null) {
                return View( theRoleInfo );
            } else {
                return RedirectTo( "Index" );
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRole(UserRoleInfo userRoleInfo) {

            if(ModelState.IsValid) {
                var theRole = (from r in userDb.Roles
                               where r.Id == userRoleInfo.roleID
                               select r).FirstOrDefault();

                if(theRole != null) {
                    theRole.Name = userRoleInfo.roleName;
                    userDb.Entry( theRole ).State = EntityState.Modified;
                    userDb.SaveChanges();
                    return RedirectTo( "Index", UR_BannerMsg.RoleEdited );
                } else {
                    return RedirectTo( "Index", UR_BannerMsg.RoleNotEdited );
                }

            } else {
                return View( userRoleInfo );
            }

        }

        // Get the Roles a specific User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRolesForUser(string userID) {
            if(!string.IsNullOrWhiteSpace( userID )) {
                var userManager = new UserManager<ApplicationUser>( new UserStore<ApplicationUser>( userDb ) );
                var rolesForTheUser = userManager.GetRoles( userID );
                TempData["rolesForTheUser"] = rolesForTheUser.Count != 0 ? rolesForTheUser : null;
                TempData["theUserID"] = userID;
            }

            return RedirectTo( "Index" );
        }

        // Delete a Role from a User
        public ActionResult DeleteRoleFromUser(string userID, string roleName) {
            if(roleName != null) {
                var userManager = new UserManager<ApplicationUser>( new UserStore<ApplicationUser>( userDb ) );

                if(userManager.IsInRole( userID, roleName )) {
                    userManager.RemoveFromRole( userID, roleName );
                    return RedirectTo( "Index", UR_BannerMsg.RoleRemovedUser );
                } else {
                    return RedirectTo( "Index", UR_BannerMsg.RoleNotRemovedUser );
                }
            }
            return RedirectTo( "Index", UR_BannerMsg.RoleNotRemovedUser );
        }

        // Add a Role to a User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRoleToUser(string userID, string roleID) {
            var roleName = from r in userDb.Roles
                           where r.Id == roleID
                           select r.Name;

            if(roleName != null) {
                var userManager = new UserManager<ApplicationUser>( new UserStore<ApplicationUser>( userDb ) );
                userManager.AddToRole( userID, roleName.FirstOrDefault() );
                return RedirectTo( "Index", UR_BannerMsg.RoleAddedUser );
            } else {
                return RedirectTo( "Index", UR_BannerMsg.RoleNotAddedUser );
            }
        }


    }

}

WebSite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using WebSite.ViewModels
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SentiMeter - @ViewBag.TitleTail</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,500&amp;subset=greek,greek-ext,latin-ext" rel="stylesheet">
    @Styles.Render( "~/Content/css" )
    <link href="@Url.Content( "~/Content/general.css" )" rel="stylesheet" type="text/css" />
    @RenderSection( "Styles", required: false )

    @Scripts.Render( "~/bundles/jquery" )
    @Scripts.Render( "~/bundles/bootstrap" )
    @Scripts.Render( "~/bundles/modernizr" )
</head>
<body>
    @{
        var navbarDropdownClass = "";
        if(ViewContext.RouteData.Values["controller"].ToString() == "MyRequests") {
            navbarDropdownClass = "open";
        }
    }
    <!-- Wrapper -->
    <div id="wrapper" class="toggled">
        <div class="overlay"></div>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                    <a href="@Url.Action( "Index", "Home", routeValues: null )">
                        <div id="logoNavDiv">
                            <img id="logoNav" src="@Url.Content("~/Content/Images/logo_small.png")" class="img-responsive" alt="">
                            SentiMeter
                        </div>
                    </a>
                </li>
                <li class="homeNavLink">
                    <a href="@String.Format( "{0}#intro", Url.Action( "Index", "Home", routeValues: null ) )"><i class="fa fa-fw fa-home nav-icon"></i><span class="nav-text">Home</span></a>
                </li>
                <li class="homeNavLink">
                    <a href="@String.Format( "{0}#about", Url.Action( "Index", "Home", routeValues: null ) )"><i class="fa fa-fw fa-question-circle nav-icon"></i><span class="nav-text">About</span></a>
                </li>
                <li class="homeNavLink">
                    <a href="@String.Format( "{0}#contact", Url.Action( "Index", "Home", routeValues: null ) )"><i class="fa fa-fw fa-phone-square nav-icon"></i><span class="nav-text">Contact</span></a>
                </li>

                @if(Request.IsAuthenticated) {
                    <li id="newRequestNavLink">
                        <a href="@Url.Action( "Create", "MyRequests", routeValues: null )"><i class="fa fa-fw fa-plus nav-icon"></i><span class="nav-text">New Request</span></a>
                    </li>
                    <li id="myRequestsNavLink" class="dropdown keep-open @navbarDropdownClass">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-search nav-icon"></i><span class="nav-text">My Requests</span><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-header">Categories</li>
                            <li>
                                <a href="@Url.Action( "Index", "MyRequests", routeValues: new { category=Category.All} )">All</a>
                            </li>
                            <li>
                                <a href="@Url.Action( "Index", "MyRequests", routeValues: new { category=Category.Pending} )">Pending</a>
                            </li>
                            <li>
                                <a href="@Url.Action( "Index", "MyRequests", routeValues: new { category=Category.Completed} )">Completed</a>
                            </li>
                            <li>
                                <a href="@Url.Action( "Index", "MyRequests", routeValues: new { category=Category.Drafts} )">Drafts</a>
                            </li>
                        </ul>
                    </li>

                    if(User.IsInRole( "Admin" )) {
                        <li id="dashboardNavLink">
                            <a href="@Url.Action( "Index", "UserRoles", routeValues: null )"><i class="fa fa-fw fa-columns nav-icon"></i><span class="nav-text">Dashboard</span></a>
                        </li>
                    }

                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-user nav-icon"></i><span class="nav-text">Account</span><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-header">Categories</li>
                            <li>
                                <a href="@Url.Action( "Index", "Manage", routeValues: null )"><i class="fa fa-fw fa-cogs nav-icon"></i><span class="nav-text">Settings</span></a>
                            </li>

                            @using(Html.BeginForm( "LogOff", "Account", FormMethod.Post, new { id = "logoutForm" } )) {
                                @Html.AntiForgeryToken()
                                <li>
                                    <a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-fw fa-sign-out nav-icon"></i><span class="nav-text">Log Out</span></a>
                                </li>
                            }
                        </ul>
                    </li>
                } else {
                    <li>
                        <a href="@Url.Action( "Register", "Account", routeValues: null )"><i class="fa fa-fw fa-user-plus nav-icon"></i><span class="nav-text">Register</span></a>
                    </li>
                    <li>
                        <a href="@Url.Action( "Login", "Account", routeValues: null )"><i class="fa fa-fw fa-sign-in nav-icon"></i><span class="nav-text">Log In</span></a>
                    </li>
                }

            </ul>

        </nav><!-- Sidebar End -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-open" data-toggle="offcanvas">
                <span class="hamb-top"></span>
                <span class="hamb-middle"></span>
                <span class="hamb-bottom"></span>
            </button>

            @RenderBody()

            <footer class="container-fluid">
                &copy;2017 SentiMeter. All Rights Reserved.
            </footer>
        </div><!-- Page Content End -->  

    </div><!-- Wrapper End -->

    @RenderSection( "Scripts", required: false )
</body>
</html>